version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:      
      - npm rebuild --update-binary # rebuild compiled pkgs without messing with yarn.lock      
      - make server
      # node_modules are checked in, so that bits tested locally are same used in test,staging and production
      - npm prune --production #remove devDependencies to shrink filesize      
      - cd node_modules && rm -rf typescript jest
      - cd ..
      - ls -al
      - mkdir deploy
      - zip -r deploy/lambda.zip dist/ node_modules > /dev/null
      - ls -al deploy/lambda.zip
      - aws cloudformation package --template-file sam-template.yml --s3-bucket $DEPLOY_BUCKET --output-template-file outputtemplate.yaml
artifacts:
  type: zip
  files:
    - sam-template.yml
    - outputtemplate.yaml